### ISSUE TITLE
Stuff we need to add

### ISSUE THREAD

**Issue by Natan515** [Imperial-Dev-Team/Imp-Website#3]
Yo, so we need to change the background image, to something u guys like, or a video. Add the sound u want (dm me de picture and sound u want me to do.) We need to add more text, in players sections, and on info. We also need to decide what to do with the donation thing, if we want to have a place for people to donate to this group or to just remove this section.

**Comment by Natan515** [comment]
Or u can just write here what video and sound u want

**Comment by Natan515** [comment]
Should I use this? https://tenor.com/view/imperial-imperials-2b2t-autoexp-9b9t-gif-19015096

**Comment by vyrsh** [comment]
does it have to be a gif?

**Comment by Natan515** [comment]
@AfkBranta Change About so it will write https://imperial-dev-team.github.io/Imp-Website/Index.html

**Comment by Natan515** [comment]
And I fixed the music, now we just need to change the background picture and add more text

**Comment by atnarb** [comment]
wtf did you guys do

**Comment by Natan515** [comment]
Dude shut up

**Comment by Natan515** [comment]
Well, I'm done.
